# WebSocket服务ip
server = "a"

# 客户端名字
client = "a"

# 客户端类型
client_type = "velocity"

# 唯一验证id
uuid = "a"

# WebSocket保护等待(单位s
wait = 60

# 主前缀
main_prefix = "§8[§6testServerName§8]"

# 在此处填写 MCDR 命令的前缀,支持多个MCDR命令前缀，如果没有使用 MCDR 开服的请保持默认，如果使用 MCDR 开服请根据实际情况填写
mcdr_command_prefix = ["!!"]

# 子服前缀
[sub_prefix]
    lobby = "§8[§alobby§8]"
